version: "3"

services:

    web:
        build: ./www
        restart: always
        container_name: course_web
        ports:
            - "8888:3333"
        volumes:
            # Linkear la carpeta www del host con la carpeta www dentro del contenedor
            - "./www/:/www/"
        depends_on: 
            - db

    db:
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - course_vol:/var/lib/postgresql/data
        container_name: course_db
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: test

    control:
        restart: always
        image: adminer
        ports:
            - "80:8080"
        container_name: course_contol
        depends_on:
            - db

volumes:
    course_vol: